import StepItem from "./StepItem";

export default function SetupStepper() {

    return (

        <div className="flex h-fit flex-col p-3">

            {/* Logo */}

            {/* <img
                src="/logo.png"
                alt="Keyzoo"
                className="h-12"
            /> */}

            {/* Heading */}

            <div className="mt-0">

                <h2 className="text-xl font-bold text-white">

                    Enable Two-Factor Authentication

                </h2>

                <p className="mt-1 text-sm text-gray-400">

                    Protect your Keyzoo Admin account with
                    another layer of security.

                </p>

            </div>

            {/* Steps */}

            <div className="mt-10 space-y-5">

                <StepItem

                    completed

                    number={1}

                    title="Scan QR Code"

                    description="Use your authenticator app to scan the QR code."

                />
                

                <StepItem

                    active

                    number={2}

                    title="Verify Code"

                    description="Enter the 6-digit code generated by your authenticator."

                />

                <StepItem

                    number={3}

                    title="Enable 2FA"

                    description="Your admin account becomes protected."

                />

            </div>

            {/* Bottom Card */}

            <div className="mt-10 rounded-2xl border border-white/10 bg-white/[0.03] p-6">

                <div className="flex items-center gap-3">

                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600/15">

                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="h-6 w-6 text-indigo-400"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >

                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2h-1V9a5 5 0 00-10 0v2H6a2 2 0 00-2 2v6a2 2 0 002 2z"
                            />

                        </svg>

                    </div>

                    <h4 className="text-lg font-semibold text-white">

                        Your Security Matters

                    </h4>

                </div>

                <p className="mt-5 text-gray-400">

                    Two-factor authentication helps protect your
                    administrator account even if someone learns
                    your password.

                </p>

            </div>

        </div>

    );

}