import '@/styles/globals.css';
import { Provider } from 'react-redux';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Head from 'next/head';
import { ThemeProvider } from 'next-themes'
// import { Toaster } from 'react-hot-toast';
import Router from 'next/router';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';
import { store } from '@/store/store';
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { loadCart } from "@/store/cartSlice";
import Maintenance from '@/components/Maintenance';
import { AuthProvider } from '@/context/AuthContext';
import { Toaster, toast } from 'sonner'
import PageLoader from "@/components/PageLoader";
import 'react-loading-skeleton/dist/skeleton.css';
import { SkeletonTheme } from 'react-loading-skeleton';
import TermlyCMP from '@/components/TermlyCMP'
import { Onest } from 'next/font/google';
// import { AdminProvider } from "@/context/AdminContext";

const onest = Onest({ subsets: ['latin'] });

// Optional: Configure NProgress
NProgress.configure({ showSpinner: false }); // only bar

Router.events.on('routeChangeStart', () => {
  NProgress.start();
});

Router.events.on('routeChangeComplete', () => {
  NProgress.done();
});

Router.events.on('routeChangeError', () => {
  NProgress.done();
});


function CartLoader({ children }) {
  const dispatch = useDispatch();

  useEffect(() => {
    const storedCart = localStorage.getItem("cart");
    if (storedCart) {
      dispatch(loadCart(JSON.parse(storedCart)));
    }
  }, [dispatch]);

  return children;
}

const WEBSITE_UUID = process.env.NEXT_PUBLIC_TERMLY_WEBSITE_UUID;

export default function MyApp({ Component, pageProps }) {

  const [pageLoading, setPageLoading] = useState(false);

  const [maintenanceChecked, setMaintenanceChecked] = useState(false);
  const [isMaintenance, setIsMaintenance] = useState(false);

  useEffect(() => {
    const handleStart = () => setPageLoading(true);
    const handleStop = () => setPageLoading(false);

    Router.events.on("routeChangeStart", handleStart);
    Router.events.on("routeChangeComplete", handleStop);
    Router.events.on("routeChangeError", handleStop);

    return () => {
      Router.events.off("routeChangeStart", handleStart);
      Router.events.off("routeChangeComplete", handleStop);
      Router.events.off("routeChangeError", handleStop);
    };
  }, []);

  useEffect(() => {
    const checkMaintenance = async () => {
      const pathname = window.location.pathname;

      // Admin should always remain accessible.
      if (pathname.startsWith("/admin")) {
        setMaintenanceChecked(true);
        return;
      }

      // Maintenance page itself should remain accessible.
      if (pathname === "/maintenance") {
        setMaintenanceChecked(true);
        return;
      }

      try {
        const API_URL = process.env.NEXT_PUBLIC_API_URL;

        const res = await fetch(
          `${API_URL}/maintenance/status`,
          {
            cache: "no-store",
          }
        );

        if (!res.ok) {
          setIsMaintenance(false);
          return;
        }

        const data = await res.json();

        setIsMaintenance(
          data?.data?.enabled === true
        );
      } catch (error) {
        console.error(
          "Maintenance mode check failed:",
          error
        );

        // Fail open:
        // if backend maintenance check fails,
        // don't block the storefront.
        setIsMaintenance(false);
      } finally {
        setMaintenanceChecked(true);
      }
    };

    checkMaintenance();
  }, []);

  if (!maintenanceChecked) {
    return null;
  }

  if (
    isMaintenance &&
    typeof window !== "undefined" &&
    window.location.pathname !== "/maintenance" &&
    !window.location.pathname.startsWith("/admin")
  ) {
    return <Maintenance />;
  }

  return (
    <>
      <main className={onest.className}>
        {/* <Head> */}
        {/* <title>Online Shoe Store | JS Dev Hindi</title> */}
        {/* <meta
          name="description"
          content="Generated by create next app"
        /> */}
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        /> */}
        {/* <link rel="icon" href="http://localhost:1337/uploads/Untitled_design_14_1_1_30fe7c121e.png" /> */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        /> */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Onest:wght@100..900&display=swap" rel="stylesheet" /> */}
        {/* </Head> */}
        {/* <AdminProvider> */}
        <ThemeProvider attribute="class">
          <TermlyCMP websiteUUID={WEBSITE_UUID} />
          {/* <SessionProvider session={session}> */}
          <AuthProvider>
            <Provider store={store}>
              <CartLoader>
                {pageLoading && <PageLoader />}
                <SkeletonTheme baseColor="#202020" highlightColor="#444">
                  <div className="flex flex-col min-h-screen">
                    <Header />
                    <main className="flex-grow">
                      <Component {...pageProps} />
                      {/* <Toaster position="top-right" /> */}
                      <Toaster
                        position="bottom-right"
                        richColors
                        expand
                        duration={3500}
                      />
                    </main>
                    <Footer />
                  </div>
                </SkeletonTheme>
              </CartLoader>
            </Provider>
          </AuthProvider>
          {/* </SessionProvider> */}
        </ThemeProvider>
        {/* </AdminProvider> */}
      </main>
    </>
  );
}
